title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
#prefix: /rosindustrial-website
# Build settings
plugins:
  - jekyll-feed

collections:
  people:
    output: true
  robots:
    output: true
  events:
    output: true
    sort_by: start_date
  history:
    output: true
  members:
    output: true
